version: '3.3'
services:
  target-data-viz:
    image: sc-registry.fredhutch.org/target-data-viz-preview:latest
    environment:
      - SHINY_LOG_STDERR=1
    networks:
      - proxy
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.target-data-viz-preview.rule=Host(`meshinchi-data-viz-preview.fredhutch.org`)"
        - "traefik.http.routers.target-data-viz-preview-secured.rule=Host(`meshinchi-data-viz-preview.fredhutch.org`)"
        - "traefik.http.routers.target-data-viz-preview.entrypoints=web,web-secured"
        - "traefik.http.services.target-data-viz-preview.loadbalancer.server.port=3838" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.target-data-viz-preview.tls=true"

networks:
  proxy:
    external: true
